# Generated by Django 4.2.23 on 2025-08-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold'), ('duration', 'Duration')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', '>'), ('lt', '<'), ('eq', '=')], max_length=2)),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('state_is_open', models.BooleanField(default=True)),
                ('state_started', models.DateTimeField(blank=True, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='alerts.alert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
