# Generated by Django 4.2.23 on 2025-08-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='state_is_open',
            field=models.BooleanField(default=False),
        ),
    ]
