### Register a new user
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "yousef123",
  "email": "yousef@example.com",
  "first_name": "Yousef",
  "last_name": "Ali",
  "password": "StrongPass123!",
  "password_confirm": "StrongPass123!"
}

###

### Login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "yousef123",
  "password": "StrongPass123!"
}

###

### Get current user info (after login)
GET http://127.0.0.1:8000/api/user/
Authorization: Bearer {token}
from