### 1) تسجيل الدخول (JWT Token)
POST http://localhost:8000/api/v1/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

### 2) تحديث التوكن (Refresh)
POST http://localhost:8000/api/v1/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTQwNTQwMiwiaWF0IjoxNzU0ODAwNjAyLCJqdGkiOiIwYWYyOGI5ZDY4OTY0YjRlYjEzNTZjZWU3NWIxZTBlOCIsInVzZXJfaWQiOiIxIn0.hVG81x7p93CIG7lS4xO1QC0Kt-_YUgF8f9sAQbCaKRY"
}

###

### 3) جلب قائمة الـ Alerts (Protected)
GET http://localhost:8000/api/alerts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0ODA0MDE3LCJpYXQiOjE3NTQ4MDA0MTcsImp0aSI6IjliOWY1OWNjOWZhMDQ5YjhiZDk5YzMwYTkxMTFkNTg4IiwidXNlcl9pZCI6IjEifQ.X8w8pSHbK3qu25xNtYUlKFtMeEH_pMecPVx9XaJOw1g

###

### 4) إنشاء Alert جديد (Protected)
POST http://localhost:8000/api/alerts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0ODA0MDE3LCJpYXQiOjE3NTQ4MDA0MTcsImp0aSI6IjliOWY1OWNjOWZhMDQ5YjhiZDk5YzMwYTkxMTFkNTg4IiwidXNlcl9pZCI6IjEifQ.X8w8pSHbK3qu25xNtYUlKFtMeEH_pMecPVx9XaJOw1g
Content-Type: application/json

{
  "title": "ختبار",
  "message": "رسالة تنبيه للتجربة"
}

###

### 5) جلب الـ API Root (للتأكد من الربط)
GET http://localhost:8000/api/

### Get my profile
GET http://localhost:8000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0ODMyNTAxLCJpYXQiOjE3NTQ4Mjg5MDEsImp0aSI6IjU1NzBmM2QzYWVjYTRjNjk5ZmFkYjliNTY4ZWZkNjdjIiwidXNlcl9pZCI6IjEifQ.SRZyfEkxpsVCYFtYQhJP6Of_5-kFldXvXPdVOSSMuGA

###

### Update my profile (partial)
PATCH http://localhost:8000/api/users/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0ODMyNTAxLCJpYXQiOjE3NTQ4Mjg5MDEsImp0aSI6IjU1NzBmM2QzYWVjYTRjNjk5ZmFkYjliNTY4ZWZkNjdjIiwidXNlcl9pZCI6IjEifQ.SRZyfEkxpsVCYFtYQhJP6Of_5-kFldXvXPdVOSSMuGA
Content-Type: application/json

{
  "first_name": "",
}
